<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{f1943cf0-4542-4ac6-8c5d-d98559e49964}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbCounter : FB_Counter;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbCounter.M_AddCounterValue();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>